### ISSUE TITLE
Getting error java.lang.NoClassDefFoundError: javax/xml/bind/JAXBContext for java 9 version

### ISSUE THREAD

**Issue by Anurag599** [NetsOSS/headless-burp#34]
java.lang.NoClassDefFoundError: javax/xml/bind/JAXBContext
	at eu.nets.burp.BurpConfiguration.loadConfiguration(BurpConfiguration.java:31)
	at eu.nets.burp.BurpConfiguration.<init>(BurpConfiguration.java:26)
	at burp.BurpExtender.processCommandLineArguments(BurpExtender.java:138)
	at burp.BurpExtender.registerExtenderCallbacks(BurpExtender.java:55)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at burp.ab5.lambda$registerExtenderCallbacks$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBContext
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 14 more
Please help me on below contact details:
email: Kumaranurag599@gmail.com
mobile: 8951650400

**Comment by tdev-cybertix-ai** [comment]
This workaround worked for me and you may also find it interesting.

The failure occurred because Java 11+ no longer includes JAXB in the JDK. The module declared only `jaxb-api` (interfaces) and produced a fat JAR via the assembly plugin, so no JAXB **implementation** was present and required `META-INF/services` entries were not merged, resulting in `ClassNotFoundException: javax.xml.bind.JAXBContext`.

The `pom.xml` was adjusted to include the JAXB runtime and activation libraries—`org.glassfish.jaxb:jaxb-runtime:2.3.1` and `com.sun.activation:javax.activation:1.2.0`—and to align `javax.xml.bind:jaxb-api` to version `2.3.1`. The packaging was switched to `maven-shade-plugin`, attaching a `-jar-with-dependencies` artifact and enabling service resource merging (via `ServicesResourceTransformer`) while disabling the dependency-reduced POM. This produces a self-contained JAR that loads correctly on Java 11+.


```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>eu.nets.burp</groupId>
    <artifactId>headless-burp</artifactId>
    <version>master-SNAPSHOT</version>
  </parent>

  <artifactId>headless-burp-scanner</artifactId>

  <dependencies>
    <!-- Burp API -->
    <dependency>
      <groupId>net.portswigger.burp.extender</groupId>
      <artifactId>burp-extender-api</artifactId>
    </dependency>

    <!-- args4j as before -->
    <dependency>
      <groupId>args4j</groupId>
      <artifactId>args4j</artifactId>
    </dependency>

    <!-- JAXB (Java 11+): API + runtime + activation -->
    <!-- Use javax.* namespace so no code changes needed -->
    <dependency>
      <groupId>javax.xml.bind</groupId>
      <artifactId>jaxb-api</artifactId>
      <version>2.3.1</version>
    </dependency>
    <dependency>
      <groupId>org.glassfish.jaxb</groupId>
      <artifactId>jaxb-runtime</artifactId>
      <version>2.3.1</version>
    </dependency>
    <dependency>
      <groupId>com.sun.activation</groupId>
      <artifactId>javax.activation</artifactId>
      <version>1.2.0</version>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <!-- Build a single self-contained JAR -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-shade-plugin</artifactId>
        <version>3.5.0</version>
        <executions>
          <execution>
            <phase>package</phase>
            <goals><goal>shade</goal></goals>
            <configuration>
              <!-- attach as *-jar-with-dependencies.jar so your parent still finds it -->
              <shadedArtifactAttached>true</shadedArtifactAttached>
              <shadedClassifierName>jar-with-dependencies</shadedClassifierName>

              <!-- make sure ServiceLoader files are merged (needed by JAXB) -->
              <transformers>
                <transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>
                <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer"/>
              </transformers>

              <!-- don’t generate a dependency-reduced POM (avoids parent clashes) -->
              <createDependencyReducedPom>false</createDependencyReducedPom>
            </configuration>
          </execution>
        </executions>
      </plugin>

      <!-- (Optional) keep compiler setup inherited from parent -->
    </plugins>
  </build>
</project>
```

Once this changes are made in the file `headless-burp/headless-burp-scanner/pom.xml` (from the original [headless burp giuthub repo](https://github.com/NetsOSS/headless-burp)), we can re-build the complete Headless BurpSuite project running `./mvnw` from the repo's root directory.
